server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: order_notifications
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update  # create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        web: DEBUG

admin:
  registration-secret: mySuperSecretKey123
