server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/orderdb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:order_notifications}
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

  jpa:
    hibernate:
      ddl-auto: update  # create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        generate_statistics: true

  integration:
    redis:
      lock:
        registry:
          expiry-time: 30000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        orm.jpa: DEBUG
        transaction: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
      stat: DEBUG

admin:
  registration-secret: ${ADMIN_REGISTRATION_SECRET}
