server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/orderdb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:order_notifications}
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

  jpa:
    hibernate:
      ddl-auto: update  # create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        web: DEBUG

admin:
  registration-secret: ${ADMIN_REGISTRATION_SECRET}
